on:
  push:
    branches:
    - master
name: Build and deploy .NET Core app to Linux WebApp new

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Install dependencies
      run: dotnet restore samplereactproject
    
    - name: Build
      run: dotnet build samplereactproject --configuration Release --no-restore
    
    - name: Publish artifact
      run: dotnet publish samplereactproject --configuration Release --no-build --output samplereactproject/publish
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: noooooooooooodelinux
        general-settings-json: '{"linuxFxVersion": "DOTNETCORE|3.1"}' #'General configuration settings as Key Value pairs'
    
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: noooooooooooodelinux
        package: samplereactproject/publish

    - name: logout
      run: |
        az logout
