on:
  push:
    branches:
    - master
name: Build and deploy, .NET Core app to Linux WebApp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Install dependencies
      run: dotnet restore samplereactreduxproject
    
    - name: Build
      run: dotnet build samplereactreduxproject --configuration Release --no-restore
    
    - name: Publish artifact
      run: dotnet publish samplereactreduxproject --configuration Release --no-build --output samplereactreduxproject/publish
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: imnotbatman
        general-settings-json: '{"linuxFxVersion": "DOTNETCORE|3.1"}' #'General configuration settings as Key Value pairs'
    
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: imnotbatman
        package: samplereactreduxproject/publish
        startup-command: dotnet run

    - name: logout
      run: |
        az logout
